# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/admin/Desktop/afterSRAM/board/test/func_test_v0.01_n4ddr/soc_sram_func/run_vivado/soc_lite.xdc

# IP: C:/Users/admin/Desktop/afterSRAM/board/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet

# IP: C:/Users/admin/Desktop/afterSRAM/board/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet
